{% set name = "pyremap" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 511dd3756aefe5a8d5d8f1cc28fcf5b46e249eeb3d379bc33386e94c8be088a7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - netcdf4
    - xarray >=0.10.0
    - dask
    - nco >=4.8.1
    - esmf
    - pyproj

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pyremap
  imports:
    - pyremap

about:
  home: https://github.com/MPAS-Dev/pyremap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python remapping tools for climate and earth system models.
  doc_url: https://pyremap.readthedocs.io/en/latest/
  dev_url: https://github.com/MPAS-Dev/pyremap

extra:
  recipe-maintainers:
    - xylar
