{% set name = "pyremap" %}
{% set version = "2.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MPAS-Dev/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e29c4fb98bdd626f5eed4b6b8fdb34dd72eda634d5dcc37a08d0e71cb739f00c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - netcdf4
    - xarray >=0.10.0
    - dask
    - nco >=4.8.1
    - esmf
    - pyproj

test:
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest --pyargs tests
  imports:
    - pyremap

about:
  home: https://github.com/MPAS-Dev/pyremap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python remapping tools for climate and earth system models.
  doc_url: https://pyremap.readthedocs.io/en/latest/
  dev_url: https://github.com/MPAS-Dev/pyremap

extra:
  recipe-maintainers:
    - altheaden
    - xylar
