schema_version: 1

context:
  name: pyremap
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MPAS-Dev/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 511dd3756aefe5a8d5d8f1cc28fcf5b46e249eeb3d379bc33386e94c8be088a7

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - netcdf4
    - xarray >=0.10.0
    - dask
    - nco >=4.8.1
    - esmf
    - pyproj

tests:
  - python:
      imports:
        - pyremap
  - requirements:
      run:
        - pytest
    script:
      - pytest --pyargs pyremap

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python remapping tools for climate and earth system models.
  homepage: https://github.com/MPAS-Dev/pyremap
  repository: https://github.com/MPAS-Dev/pyremap
  documentation: https://pyremap.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - altheaden
    - xylar

